"""Predefined categories and realistic seed catalog for dummy product import.
All prices in INR (₹) with realistic retail descriptions.
"""

from typing import Any

PREDEFINED_CATEGORIES: list[dict[str, str]] = [
    {
        "name": "Fashion",
        "emoji": "👗",
        "slug": "fashion",
        "description": "Apparel, footwear, and trending everyday wear",
    },
    {
        "name": "Electronics",
        "emoji": "📱",
        "slug": "electronics",
        "description": "Gadgets, audio, accessories, and smart devices",
    },
    {
        "name": "Home Decor",
        "emoji": "🏡",
        "slug": "home-decor",
        "description": "Lamps, wall art, cushions, and aesthetic accents",
    },
    {
        "name": "Grocery",
        "emoji": "🥑",
        "slug": "grocery",
        "description": "Pantry essentials, gourmet snacks, and organic staples",
    },
    {
        "name": "Beauty",
        "emoji": "💄",
        "slug": "beauty",
        "description": "Skincare, haircare, fragrances, and daily wellness",
    },
    {
        "name": "Books",
        "emoji": "📚",
        "slug": "books",
        "description": "Bestselling fiction, self-help, and indie titles",
    },
    {
        "name": "Toys",
        "emoji": "🧸",
        "slug": "toys",
        "description": "Educational puzzles, plush toys, and STEM games",
    },
    {
        "name": "Jewellery",
        "emoji": "💍",
        "slug": "jewellery",
        "description": "Minimalist silver, brass accents, and handcrafted gems",
    },
]

# 8 categories x 8 products each = 64 realistic items
SEED_PRODUCTS_BY_CATEGORY: dict[str, list[dict[str, Any]]] = {
    "Fashion": [
        {
            "name": "Oversized Cotton Tee",
            "description": "Breathable 240 GSM combed cotton t-shirt with drop-shoulder fit.",
            "price": 799.00,
            "compare_at_price": 1299.00,
            "discount_pct": 38,
            "stock": 45,
            "sku": "FSH-TEE-01",
            "image_url": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Slim Fit Raw Denim",
            "description": "Classic Japanese selvage-style indigo denim with slight stretch comfort.",
            "price": 2499.00,
            "compare_at_price": 3499.00,
            "discount_pct": 28,
            "stock": 25,
            "sku": "FSH-JNS-02",
            "image_url": "https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Linen Mandarin Collar Shirt",
            "description": "Pre-washed 100% pure linen casual shirt for summer comfort.",
            "price": 1899.00,
            "compare_at_price": 2299.00,
            "discount_pct": 17,
            "stock": 30,
            "sku": "FSH-SHR-03",
            "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Cashmere Blend Cardigan",
            "description": "Ultra-soft knit cardigan with horn buttons and ribbed cuffs.",
            "price": 3199.00,
            "compare_at_price": 4499.00,
            "discount_pct": 28,
            "stock": 18,
            "sku": "FSH-SWT-04",
            "image_url": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Classic Canvas Low Sneakers",
            "description": "Everyday vulcanized sneakers with cushioned insole and non-slip rubber sole.",
            "price": 1499.00,
            "compare_at_price": 1999.00,
            "discount_pct": 25,
            "stock": 40,
            "sku": "FSH-SNK-05",
            "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Structured Crossbody Bag",
            "description": "Vegan textured leather bag with adjustable strap and brass hardware.",
            "price": 1999.00,
            "compare_at_price": 2799.00,
            "discount_pct": 28,
            "stock": 22,
            "sku": "FSH-BAG-06",
            "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Pleated Midi Skirt",
            "description": "Fluid satin finish accordion pleated skirt with elasticated waist.",
            "price": 1699.00,
            "compare_at_price": 2199.00,
            "discount_pct": 22,
            "stock": 20,
            "sku": "FSH-SKT-07",
            "image_url": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Handwoven Wool Scarf",
            "description": "Lightweight merino wool wrap with tasseled hem, dyed with natural pigments.",
            "price": 999.00,
            "compare_at_price": 1499.00,
            "discount_pct": 33,
            "stock": 35,
            "sku": "FSH-SCF-08",
            "image_url": "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Electronics": [
        {
            "name": "Wireless Noise Cancelling Earbuds",
            "description": "Active noise cancellation with 32-hour playback and IPX5 water resistance.",
            "price": 2999.00,
            "compare_at_price": 4999.00,
            "discount_pct": 40,
            "stock": 50,
            "sku": "ELC-EBD-01",
            "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "65W GaN Fast Charger",
            "description": "Dual USB-C and USB-A compact gallium nitride charger for laptop and phone.",
            "price": 1699.00,
            "compare_at_price": 2199.00,
            "discount_pct": 22,
            "stock": 60,
            "sku": "ELC-CHG-02",
            "image_url": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Mechanical Keyboard RGB",
            "description": "Hot-swappable tactile brown switches with backlit double-shot PBT keycaps.",
            "price": 3899.00,
            "compare_at_price": 5499.00,
            "discount_pct": 29,
            "stock": 20,
            "sku": "ELC-KBD-03",
            "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "10000mAh Magnetic Power Bank",
            "description": "MagSafe-compatible 15W wireless power bank with folding kickstand.",
            "price": 2199.00,
            "compare_at_price": 2999.00,
            "discount_pct": 26,
            "stock": 35,
            "sku": "ELC-PWR-04",
            "image_url": "https://images.unsplash.com/photo-1609592807908-1e0e84b6f125?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Portable Bluetooth Speaker",
            "description": "Deep bass 360-degree sound with rugged waterproof casing and 14h battery.",
            "price": 2499.00,
            "compare_at_price": 3499.00,
            "discount_pct": 28,
            "stock": 28,
            "sku": "ELC-SPK-05",
            "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "4K Ultra HD Web Camera",
            "description": "Auto-focus wide-angle webcam with dual noise-reducing microphones.",
            "price": 3299.00,
            "compare_at_price": 4299.00,
            "discount_pct": 23,
            "stock": 15,
            "sku": "ELC-CAM-06",
            "image_url": "https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Smart Fitness Smartwatch",
            "description": "Heart rate, SpO2 tracking, AMOLED touch display with 7-day battery life.",
            "price": 2799.00,
            "compare_at_price": 4499.00,
            "discount_pct": 37,
            "stock": 30,
            "sku": "ELC-WTC-07",
            "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Ergonomic Vertical Mouse",
            "description": "Wireless 2.4GHz + Bluetooth rechargeable mouse reducing wrist strain.",
            "price": 1299.00,
            "compare_at_price": 1799.00,
            "discount_pct": 27,
            "stock": 42,
            "sku": "ELC-MSE-08",
            "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Home Decor": [
        {
            "name": "Ceramic Ribbed Vase",
            "description": "Handcrafted terracotta ribbed flower vase with matte ivory glaze finish.",
            "price": 899.00,
            "compare_at_price": 1299.00,
            "discount_pct": 30,
            "stock": 25,
            "sku": "HMD-VAS-01",
            "image_url": "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Boho Tufted Cushion Cover",
            "description": "Set of 2 embroidered cotton linen cushion covers with fringe detail.",
            "price": 799.00,
            "compare_at_price": 1099.00,
            "discount_pct": 27,
            "stock": 40,
            "sku": "HMD-CSH-02",
            "image_url": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Nordic Minimalist Desk Lamp",
            "description": "Warm ambient LED table lamp with solid natural beech wood base.",
            "price": 1899.00,
            "compare_at_price": 2599.00,
            "discount_pct": 26,
            "stock": 16,
            "sku": "HMD-LMP-03",
            "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Soy Wax Aromatherapy Candle",
            "description": "Hand-poured 220g lavender and vanilla scented soy candle in amber glass.",
            "price": 599.00,
            "compare_at_price": 899.00,
            "discount_pct": 33,
            "stock": 55,
            "sku": "HMD-CND-04",
            "image_url": "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Round Bamboo Wall Mirror",
            "description": "50cm diameter accent mirror framed in eco-friendly woven natural rattan.",
            "price": 2199.00,
            "compare_at_price": 2999.00,
            "discount_pct": 26,
            "stock": 12,
            "sku": "HMD-MIR-05",
            "image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Macrame Plant Hanger",
            "description": "Hand-knotted 100% cotton cord hanging planter for indoor potted plants.",
            "price": 499.00,
            "compare_at_price": 699.00,
            "discount_pct": 28,
            "stock": 35,
            "sku": "HMD-PLT-06",
            "image_url": "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Solid Wood Floating Shelf",
            "description": "Reclaimed teak wood wall shelf with concealed mounting brackets.",
            "price": 1499.00,
            "compare_at_price": 1999.00,
            "discount_pct": 25,
            "stock": 20,
            "sku": "HMD-SHF-07",
            "image_url": "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Abstract Canvas Wall Art",
            "description": "Framed gallery wrap minimal geometric canvas print (40x60 cm).",
            "price": 1299.00,
            "compare_at_price": 1799.00,
            "discount_pct": 27,
            "stock": 22,
            "sku": "HMD-ART-08",
            "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Grocery": [
        {
            "name": "Cold Pressed Mustard Oil 1L",
            "description": "Single-origin wood pressed pure mustard oil full of natural pungency.",
            "price": 280.00,
            "compare_at_price": 340.00,
            "discount_pct": 17,
            "stock": 60,
            "sku": "GRO-OIL-01",
            "image_url": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Organic Forest Honey 500g",
            "description": "Raw, unfiltered wild forest multi-floral honey with zero added sugars.",
            "price": 450.00,
            "compare_at_price": 599.00,
            "discount_pct": 24,
            "stock": 45,
            "sku": "GRO-HNY-02",
            "image_url": "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Artisanal Filter Coffee Blend 250g",
            "description": "80:20 Arabica and Peaberry roasted chicory coffee powder from Coorg.",
            "price": 320.00,
            "compare_at_price": 400.00,
            "discount_pct": 20,
            "stock": 50,
            "sku": "GRO-COF-03",
            "image_url": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Roasted California Almonds 500g",
            "description": "Slow dry roasted jumbo almonds lightly sprinkled with Himalayan pink salt.",
            "price": 599.00,
            "compare_at_price": 799.00,
            "discount_pct": 25,
            "stock": 40,
            "sku": "GRO-ALM-04",
            "image_url": "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Organic Rolled Oats 1kg",
            "description": "Gluten-free wholegrain oats high in soluble fiber and protein.",
            "price": 299.00,
            "compare_at_price": 399.00,
            "discount_pct": 25,
            "stock": 70,
            "sku": "GRO-OAT-05",
            "image_url": "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Darjeeling First Flush Tea 100g",
            "description": "Delicate champagne of teas with muscatel notes from high elevation estates.",
            "price": 499.00,
            "compare_at_price": 650.00,
            "discount_pct": 23,
            "stock": 30,
            "sku": "GRO-TEA-06",
            "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Organic Quinoa Grain 500g",
            "description": "Pre-washed white royal quinoa grain rich in all nine essential amino acids.",
            "price": 349.00,
            "compare_at_price": 450.00,
            "discount_pct": 22,
            "stock": 35,
            "sku": "GRO-QNA-07",
            "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Dark Chocolate 70% Single Origin 100g",
            "description": "Bean-to-bar Indian single origin craft chocolate with roasted cacao nibs.",
            "price": 250.00,
            "compare_at_price": 320.00,
            "discount_pct": 21,
            "stock": 60,
            "sku": "GRO-CHC-08",
            "image_url": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Beauty": [
        {
            "name": "Vitamin C Radiance Face Serum",
            "description": "15% ethyl ascorbic acid with ferulic acid to brighten skin and fade dark spots.",
            "price": 699.00,
            "compare_at_price": 999.00,
            "discount_pct": 30,
            "stock": 40,
            "sku": "BTY-SER-01",
            "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Ceramide Barrier Repair Cream",
            "description": "Rich nourishing daily moisturizer with 5 essential ceramides and hyaluronic acid.",
            "price": 549.00,
            "compare_at_price": 799.00,
            "discount_pct": 31,
            "stock": 50,
            "sku": "BTY-CRM-02",
            "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Rosemary Scalp Revitalizing Oil",
            "description": "Pure rosemary essential oil infused with bhringraj and cold-pressed castor oil.",
            "price": 499.00,
            "compare_at_price": 699.00,
            "discount_pct": 28,
            "stock": 45,
            "sku": "BTY-OIL-03",
            "image_url": "https://images.unsplash.com/photo-1608248597359-00f730c44365?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Hydrating Dewy Lip Tint",
            "description": "Non-sticky moisturizing lip oil tint enriched with jojoba and shea butter.",
            "price": 399.00,
            "compare_at_price": 550.00,
            "discount_pct": 27,
            "stock": 60,
            "sku": "BTY-LIP-04",
            "image_url": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Gentle Salicylic Gel Cleanser",
            "description": "2% BHA foaming face wash that purifies pores without stripping moisture.",
            "price": 449.00,
            "compare_at_price": 599.00,
            "discount_pct": 25,
            "stock": 35,
            "sku": "BTY-CLN-05",
            "image_url": "https://images.unsplash.com/photo-1556228722-d0b740523098?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Matte Mineral Sunscreen SPF 50+",
            "description": "Broad spectrum PA++++ zinc oxide sunscreen leaving zero white cast.",
            "price": 599.00,
            "compare_at_price": 799.00,
            "discount_pct": 25,
            "stock": 55,
            "sku": "BTY-SUN-06",
            "image_url": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Green Tea Exfoliating Clay Mask",
            "description": "Detoxifying French kaolin clay mask that reduces sebum and refines texture.",
            "price": 499.00,
            "compare_at_price": 699.00,
            "discount_pct": 28,
            "stock": 30,
            "sku": "BTY-MSK-07",
            "image_url": "https://images.unsplash.com/photo-1567928815104-b7980ee5032e?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Woody Amber Eau de Parfum 50ml",
            "description": "Long-lasting fragrance with notes of cedarwood, cardamom, and warm amber.",
            "price": 1499.00,
            "compare_at_price": 1999.00,
            "discount_pct": 25,
            "stock": 25,
            "sku": "BTY-PRF-08",
            "image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Books": [
        {
            "name": "The Art of Slow Living",
            "description": "A mindful guide to escaping burnout and finding joy in modern simplicity.",
            "price": 499.00,
            "compare_at_price": 699.00,
            "discount_pct": 28,
            "stock": 35,
            "sku": "BKS-NON-01",
            "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Midnight in the Old City",
            "description": "Atmospheric mystery novel set through winding lanes and forgotten archives.",
            "price": 399.00,
            "compare_at_price": 550.00,
            "discount_pct": 27,
            "stock": 40,
            "sku": "BKS-FIC-02",
            "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Zero to Prototype: Startup Manual",
            "description": "Actionable product strategies and engineering playbooks for early-stage builders.",
            "price": 649.00,
            "compare_at_price": 899.00,
            "discount_pct": 27,
            "stock": 28,
            "sku": "BKS-BUS-03",
            "image_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Flavors of the Subcontinent: Recipes",
            "description": "Hardcover culinary collection featuring 120 regional heirloom recipes.",
            "price": 1199.00,
            "compare_at_price": 1599.00,
            "discount_pct": 25,
            "stock": 15,
            "sku": "BKS-COK-04",
            "image_url": "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Poetry for Starlit Nights",
            "description": "Illustrated contemporary anthology exploring love, solitude, and resilience.",
            "price": 349.00,
            "compare_at_price": 499.00,
            "discount_pct": 30,
            "stock": 30,
            "sku": "BKS-POE-05",
            "image_url": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Mind Over Code: Developer Psychology",
            "description": "How top software engineers sustain focus, creative drive, and mental health.",
            "price": 599.00,
            "compare_at_price": 799.00,
            "discount_pct": 25,
            "stock": 20,
            "sku": "BKS-PSY-06",
            "image_url": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Pocket Atlas of Forgotten Stars",
            "description": "Stunning illustrated visual guide to celestial constellations and deep space.",
            "price": 799.00,
            "compare_at_price": 999.00,
            "discount_pct": 20,
            "stock": 18,
            "sku": "BKS-AST-07",
            "image_url": "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "The Craftsman's Notebook",
            "description": "Leatherette journal with thick 120gsm archival unruled bamboo paper.",
            "price": 450.00,
            "compare_at_price": 600.00,
            "discount_pct": 25,
            "stock": 50,
            "sku": "BKS-JRN-08",
            "image_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Toys": [
        {
            "name": "Wooden Solar System Puzzle",
            "description": "Montessori non-toxic handcrafted wooden planet board for kids aged 3+.",
            "price": 899.00,
            "compare_at_price": 1299.00,
            "discount_pct": 30,
            "stock": 25,
            "sku": "TOY-PZL-01",
            "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Robotics DIY STEM Starter Kit",
            "description": "Build 5 motorized bots with gears, motor, and easy visual guide.",
            "price": 1499.00,
            "compare_at_price": 2199.00,
            "discount_pct": 31,
            "stock": 20,
            "sku": "TOY-STM-02",
            "image_url": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Plush Organic Cotton Bear",
            "description": "Hypoallergenic ultra-soft cuddle teddy stuffed with recycled fiber.",
            "price": 699.00,
            "compare_at_price": 999.00,
            "discount_pct": 30,
            "stock": 35,
            "sku": "TOY-PLS-03",
            "image_url": "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Magnetic 3D Building Tiles 60pc",
            "description": "Translucent colorful magnetic tiles sparking architectural imagination.",
            "price": 1799.00,
            "compare_at_price": 2499.00,
            "discount_pct": 28,
            "stock": 30,
            "sku": "TOY-MAG-04",
            "image_url": "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Wooden Train Set with Bridge",
            "description": "Compatible magnetic wooden track system with locomotives and trees.",
            "price": 1299.00,
            "compare_at_price": 1899.00,
            "discount_pct": 31,
            "stock": 18,
            "sku": "TOY-TRN-05",
            "image_url": "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Eco Watercolor Painting Set",
            "description": "24 pigment-rich non-toxic washable watercolor cakes with 2 brushes.",
            "price": 499.00,
            "compare_at_price": 699.00,
            "discount_pct": 28,
            "stock": 45,
            "sku": "TOY-ART-06",
            "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Balance Stepping Stones Set",
            "description": "6 non-skid textured stones encouraging balance, coordination, and agility.",
            "price": 1999.00,
            "compare_at_price": 2799.00,
            "discount_pct": 28,
            "stock": 12,
            "sku": "TOY-BAL-07",
            "image_url": "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Memory Match Animal Cards",
            "description": "Thick cardstock memory card game with hand-illustrated animal portraits.",
            "price": 399.00,
            "compare_at_price": 549.00,
            "discount_pct": 27,
            "stock": 50,
            "sku": "TOY-CRD-08",
            "image_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
        },
    ],
    "Jewellery": [
        {
            "name": "925 Sterling Silver Crescent Necklace",
            "description": "Dainty crescent moon pendant on an 18-inch adjustable silver chain.",
            "price": 1499.00,
            "compare_at_price": 2199.00,
            "discount_pct": 31,
            "stock": 25,
            "sku": "JWL-NCK-01",
            "image_url": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Chunky Gold-Plated Huggie Hoops",
            "description": "18K gold plated brass hypoallergenic huggies with secure click closure.",
            "price": 899.00,
            "compare_at_price": 1299.00,
            "discount_pct": 30,
            "stock": 35,
            "sku": "JWL-EAR-02",
            "image_url": "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Raw Herkimer Diamond Ring",
            "description": "Prong-set uncut natural quartz crystal in sterling silver band.",
            "price": 1899.00,
            "compare_at_price": 2599.00,
            "discount_pct": 26,
            "stock": 15,
            "sku": "JWL-RNG-03",
            "image_url": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Hammered Brass Cuff Bracelet",
            "description": "Artisanal open cuff bracelet with tactile hand-hammered texture finish.",
            "price": 799.00,
            "compare_at_price": 1099.00,
            "discount_pct": 27,
            "stock": 28,
            "sku": "JWL-BRC-04",
            "image_url": "https://images.unsplash.com/photo-1611591475870-07e32c021175?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Freshwater Pearl Drop Earrings",
            "description": "Baroque organic shaped pearls suspended from 14K gold filled wires.",
            "price": 1299.00,
            "compare_at_price": 1799.00,
            "discount_pct": 27,
            "stock": 20,
            "sku": "JWL-PRL-05",
            "image_url": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Layered Snake Chain Choker",
            "description": "Sleek liquid-metal snake chain choker that drapes effortlessly along collarbones.",
            "price": 999.00,
            "compare_at_price": 1399.00,
            "discount_pct": 28,
            "stock": 30,
            "sku": "JWL-CHK-06",
            "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Evil Eye Mother-of-Pearl Anklet",
            "description": "Protective talisman anklet handcrafted with iridescent natural shell.",
            "price": 699.00,
            "compare_at_price": 999.00,
            "discount_pct": 30,
            "stock": 32,
            "sku": "JWL-ANK-07",
            "image_url": "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&auto=format&fit=crop&q=80",
        },
        {
            "name": "Engraved Minimal Signet Ring",
            "description": "Brushed silver unisex flat-top signet ring made with recycled metal.",
            "price": 1199.00,
            "compare_at_price": 1599.00,
            "discount_pct": 25,
            "stock": 22,
            "sku": "JWL-SGN-08",
            "image_url": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80",
        },
    ],
}
